### ISSUE TITLE
Parsed Documents Have XML Tags

### ISSUE THREAD

**Issue by LRParser** [LexPredict/openedgar#11]
I notice a lot of my parsed documents (from documents/text folder) still have XML tags in them, for instance:

    <Report instance="photozou-20161130.xml">
      <IsDefault>false</IsDefault>
      <HasEmbeddedReports>false</HasEmbeddedReports>
      <HtmlFileName>R11.htm</HtmlFileName>
      <LongName>00000011 - Disclosure - NOTE 5 INCOME TAXES</LongName>
      <ReportType>Sheet</ReportType>
      <Role>http://photozou.com/role/Note5IncomeTaxes</Role>
      <ShortName>NOTE 5 INCOME TAXES</ShortName>
      <MenuCategory>Notes</MenuCategory>
      <Position>11</Position>
    </Report>

This is hurting trying to train a word embedding model. Any tips on how to avoid this? I definitely see Tika working hard but I still see a lot of XML in my processed results. Is this expected?

**Comment by mjbommar** [comment]
@LRParser that looks like an XBRL document, which are purposefully XML.  You might try checking for `"XBRL"` in the description or common XBRL tags in the document to exclude them.
