### ISSUE TITLE
Migrations not version controlled?

### ISSUE THREAD

**Issue by DomHudson** [LexPredict/openedgar#5]
Hi, 
Just a quick question - I was wondering why the installation procedure recommends making the migrations during the install? Usually I have seen these files in version control, if they are not it can make things a bit harder so if there isn't a particular reason why I'm happy to submit a PR with them in! 

Many thanks
Dom

**Comment by mjbommar** [comment]
Hi @DomHudson, thanks for pointing this out.  We probably missed these after resetting the migrations during cleanup for open source release.  A PR to add them would be great if you have a minute!

**Comment by mjbommar** [comment]
Thanks for the PR, @DomHudson !
